version: '2.2'

services:

  mongo:
    image: 'mongo'
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: 'redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"