version: '2.2'

services:

  todo-service:
    build:
      dockerfile: Dockerfile
      context: ./todo-service
    image: todo-service:latest
    ports:
      - "8686:80"
    environment:
      - TODO_SERVICE_PORT=80
      - MONGODB_URL=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  todo-ui:
    build:
      dockerfile: Dockerfile
      context: ./todo-ui
    image: todo-ui:latest
    ports:
      - "4200:4200"
    depends_on:
      - todo-service

  mongo:
    image: 'mongo'
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: 'redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"